public class DistroWrapper{
        public List<Distribution__c> distributions {get; set;}
        public DistroWrapper() {
            distributions = new List<Distribution__c>();            
        }
    
        public void addDistribution() {            
        }
        public void removeDistribution() {            
        }       
        public void saveDistributions() {            
        }
}